version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: react-native-router-flux
    versions:
    - 4.2.0
    - 4.3.0
  - dependency-name: handlebars
    versions:
    - 4.7.6
  - dependency-name: react-native-file-picker
    versions:
    - 0.0.19
